/// Handlers module - AUTO-GENERATED by `zails build`
/// DO NOT EDIT MANUALLY - changes will be overwritten
///
/// To add a new handler:
///   1. Drop a .zig file in handlers/ directory
///   2. Export MESSAGE_TYPE, Context, and handle() function
///   3. Run `zails build`


const std = @import("std");

// Auto-imported handler modules
pub const analytics_handler = @import("analytics_handler.zig");
pub const control_handler = @import("control_handler.zig");
pub const echo_handler = @import("echo_handler.zig");
pub const example_handler = @import("example_handler.zig");
pub const metrics_handler = @import("metrics_handler.zig");
pub const ping_handler = @import("ping_handler.zig");
pub const test_handler = @import("test_handler.zig");

/// List of all handler modules (compile-time)
/// This tuple is used by HandlerRegistry for comptime dispatch
pub const handler_modules = .{
    analytics_handler,
    control_handler,
    echo_handler,
    example_handler,
    metrics_handler,
    ping_handler,
    test_handler,
};

/// Helper: get list of all registered message types (compile-time)
pub fn getAllMessageTypes() []const u8 {
    comptime {
        var types: [handler_modules.len]u8 = undefined;
        for (handler_modules, 0..) |handler_module, i| {
            types[i] = handler_module.MESSAGE_TYPE;
        }
        const final = types;
        return &final;
    }
}

/// Helper: get handler count (compile-time)
pub fn getHandlerCount() comptime_int {
    return handler_modules.len;
}

// Compile-time validation with enhanced error messages
comptime {
    // Ensure no duplicate message types
    for (handler_modules, 0..) |module_a, i| {
        for (handler_modules, 0..) |module_b, j| {
            if (i < j and module_a.MESSAGE_TYPE == module_b.MESSAGE_TYPE) {
                @compileError(std.fmt.comptimePrint(
                    "DUPLICATE MESSAGE_TYPE {d}!\n" ++
                        "  Handler 1: {s} (MESSAGE_TYPE = {d})\n" ++
                        "  Handler 2: {s} (MESSAGE_TYPE = {d})\n" ++
                        "Assign unique MESSAGE_TYPE values in each handler file.",
                    .{
                        module_a.MESSAGE_TYPE,
                        @typeName(@TypeOf(module_a)),
                        module_a.MESSAGE_TYPE,
                        @typeName(@TypeOf(module_b)),
                        module_b.MESSAGE_TYPE,
                    },
                ));
            }
        }
    }
}
